name: AutoTool
main: me.g2213swo.autotool.AutoTool
version: 0.0.1
author: g2213swo
api-version: 1.17
commands:
  autotool:
    description: AutoTool command
    usage: /<command>
    permission: default
